exports.seed = (knex, Promise) => {
  return knex("ratings").del()
    .then(() => {
      return knex("ratings").insert([{
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day!",
          question_3: "Ravenclaw",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "0",
          question_8: "Speed Up",
          question_9: "English",
          question_10: "Sci-Fi",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Hufflepuff",
          question_4: "Netflix",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2,000+",
          question_8: "Speed Up",
          question_9: "Gym",
          question_10: "Comedy",
        },
        {
          question_1: "Yes",
          question_2: "Crunch All Day!",
          question_3: "Muggle",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Fall",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "Science",
          question_10: "Drama",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Slytherin",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Math",
          question_10: "Horror",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day! ",
          question_3: "Gryfindor",
          question_4: "Club",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Arts",
          question_10: "Romance",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day!",
          question_3: "Ravenclaw",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "0",
          question_8: "Speed Up",
          question_9: "English",
          question_10: "Sci-Fi",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Slytherin",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Math",
          question_10: "Horror",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Hufflepuff",
          question_4: "Netflix",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2,000+",
          question_8: "Speed Up",
          question_9: "Gym",
          question_10: "Comedy",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Hufflepuff",
          question_4: "Netflix",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2,000+",
          question_8: "Speed Up",
          question_9: "Gym",
          question_10: "Comedy",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Hufflepuff",
          question_4: "Netflix",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2,000+",
          question_8: "Speed Up",
          question_9: "Gym",
          question_10: "Comedy",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day! ",
          question_3: "Gryfindor",
          question_4: "Club",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Arts",
          question_10: "Romance",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Slytherin",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Math",
          question_10: "Horror",
        },
        {
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day!",
          question_3: "Ravenclaw",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "0",
          question_8: "Speed Up",
          question_9: "English",
          question_10: "Sci-Fi",
        },
        {
          question_1: "Yes",
          question_2: "Crunch All Day!",
          question_3: "Muggle",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Fall",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "Science",
          question_10: "Drama",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day!",
          question_3: "Ravenclaw",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "0",
          question_8: "Speed Up",
          question_9: "English",
          question_10: "Sci-Fi",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Slytherin",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Math",
          question_10: "Horror",
        },
        {
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "Yes",
          question_2: "Role It Nicely",
          question_3: "Ravenclaw",
          question_4: "Netflix",
          question_5: "Camping",
          question_6: "Summer",
          question_7: "0",
          question_8: "Slow Down",
          question_9: "English",
          question_10: "Action",
        },
        {
          question_1: "Yes",
          question_2: "Roll It Nicely",
          question_3: "Slytherin",
          question_4: "Club",
          question_5: "Camping",
          question_6: "Spring",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Math",
          question_10: "Horror",
        },
        {
          question_1: "No",
          question_2: "Crunch All Day! ",
          question_3: "Gryfindor",
          question_4: "Club",
          question_5: "Resort",
          question_6: "Winter",
          question_7: "2000+",
          question_8: "Speed Up",
          question_9: "Arts",
          question_10: "Romance",
        },
      ]);
    });
};