exports.seed = (knex, Promise) => {
  return knex("profiles").del()
    .then(() => {
      return knex("profiles").insert([{
          first_name: "Bethany",
          last_name: "Mitch",
          url: "https://media.licdn.com/dms/image/C5103AQG-B5sJWXmTWQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=bErQVrjwyME0JQRpu1g-VLZxf8s7-8ajGPIzMLlDTp0",
          accountUser_id: 1,
          rating_id: 1,
        },
        {
          first_name: "Reid",
          last_name: "Garner",
          url: "https://media.licdn.com/dms/image/C4E03AQGXrKgm_tnF2w/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=j8zDkcQB6FrWo43N19tRDVYBdLQCTmeq96EWKcy_B_U",
          accountUser_id: 2,
          rating_id: 2,
        },
        {
          first_name: "Ben",
          last_name: "Rumsey",
          url: "https://media.licdn.com/dms/image/C4E03AQHDx8tdiYUO8w/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=fglQttW2p3W3rYVb_WW7u1o3YmY6LLI27JllsMbLctU",
          accountUser_id: 3,
          rating_id: 3,
        },
        {
          first_name: "DeBronis",
          last_name: "Warren",
          url: "https://media.licdn.com/dms/image/C5603AQHN3WwoEuuaRQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=pk3TbYEFJZMgkJwk7uWhHTF-lxJnimniaXN8Zhjw0yM",
          accountUser_id: 4,
          rating_id: 4,
        },
        {
          first_name: "Brandon",
          last_name: "RedShirt",
          url: "https://media.licdn.com/dms/image/C4E03AQGs1UT4WfCjgQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=ityhpSPoYJFNCqlWUG6yDxt6zxVgf_nXeE88G-3L7Bk",
          accountUser_id: 5,
          rating_id: 5,
        },
        {
          first_name: "Sonja ",
          last_name: "Chacon",
          url: "https://media.licdn.com/dms/image/C4E03AQGEg5ZaDPyHCQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=0kIZRE8EVpuYtPNVWk_MEIgRGgPl0Iw6sfCecXxmBZE",
          accountUser_id: 6,
          rating_id: 6,
        },
        {
          first_name: "Chia-en (Peter)",
          last_name: "Fu",
          url: "https://media.licdn.com/dms/image/C5603AQGULFwxVA73Mg/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=YR3hwswmtlkG-To8WdqwFQy5wpwdy0eDyRZsPjtpruA",
          accountUser_id: 7,
          rating_id: 7,
        },
        {
          first_name: "Gary",
          last_name: "Anderson",
          url: "https://media.licdn.com/dms/image/C5603AQE3krKwFpFC8w/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=yz5uJ8IsK9oyrD57T5TJ3xCOUtnSvlyev04oxKnoUCE",
          accountUser_id: 8,
          rating_id: 8,
        },
        {
          first_name: "Conner",
          last_name: "Chevaillier",
          url: "https://media.licdn.com/dms/image/C4E03AQGomRz4bGa2_w/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=dXzLkqkdmVzt-yId3C6CauXOHusk9gyxtXab8F1suxU",
          accountUser_id: 9,
          rating_id: 9,
        },
        {
          first_name: "Phillip",
          last_name: "Hengemuhle",
          url: "https://media.licdn.com/dms/image/C5603AQHoK7coXtrP2w/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=cST5NP9JaQR1t7JaWVFutEr7PErAS0oCu0aTXmwOgrg",
          accountUser_id: 10,
          rating_id: 10,
        },
        {
          first_name: "Greg",
          last_name: "Forney",
          url: "https://media.licdn.com/dms/image/C5603AQFrP8qbl70Bpw/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=L64jAOj-o2p9nhDS-7RomQgicnHMSzPlIzbdfV0xyBE",
          accountUser_id: 11,
          rating_id: 11,
        },
        {
          first_name: "Dane",
          last_name: "Parke",
          url: "https://media.licdn.com/dms/image/C5603AQEJLplududPZg/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=aqevXPQ9sT5C1p5HDaEG5uijTnRHhjL9HBeBc2WVn_U",
          accountUser_id: 12,
          rating_id: 12,
        },
        {
          first_name: "Joshua",
          last_name: "Scala",
          url: "https://media.licdn.com/dms/image/C4E03AQF3bGM_mVBJ7A/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=XwXFmZ5OiGp5Cu2ErroZM8bgw2Xce7tScm7LzTfxvvg",
          accountUser_id: 13,
          rating_id: 13,
        },
        {
          first_name: "Jess",
          last_name: "MarkGraf",
          url: "https://media.licdn.com/dms/image/C4E03AQH2pwIdFQ3FlQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=8uR_MeKakMLByawTx6PXJ-YQJC6Wpa6RDXlYGD9Ia-Y",
          accountUser_id: 14,
          rating_id: 14,
        },
        {
          first_name: "Robert (Trey)",
          last_name: "Young",
          url: "https://media.licdn.com/dms/image/C4E03AQEbkwPp5O1zMg/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=JzJKj8bk7v3XlsSO3QjcHMhs-0TTPFoUj19LcV9QtYA",
          accountUser_id: 15,
          rating_id: 15,
        },
        {
          first_name: "Ryan",
          last_name: "St.Germain",
          url: "https://media.licdn.com/dms/image/C4E03AQGYPPXg1PWXUw/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=HCXXGvPmBUQTePPcuQzUyzhcWzEPjOKO5cfHJaGdhVQ",
          accountUser_id: 16,
          rating_id: 16,
        },
        {
          first_name: "Evan",
          last_name: "Young",
          url: "https://media.licdn.com/dms/image/C4E03AQGfEWWrq2b2tg/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=TdQ5tmEIa6ebu2hWKeJb9IfMrpW2lZa5cB5G2JxMVhk",
          accountUser_id: 17,
          rating_id: 17,
        },
        {
          first_name: "Charity",
          last_name: "Van Buren",
          url: "https://media.licdn.com/dms/image/C5603AQER4fakvEuqfg/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=CD_I1DQ1p79DRQA1L-7QFqfj7xfgcCHPHcWPnE5khfY",
          accountUser_id: 18,
          rating_id: 18,
        },
        {
          first_name: "Andrew",
          last_name: "Pedersen",
          url: "https://media.licdn.com/dms/image/C4E03AQEpxR0WN9GdcQ/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=DRVGdYnR5Z29g2SaC4EZTa5teUg357zCtVdrVP-hnRY",
          accountUser_id: 19,
          rating_id: 19,
        },
        {
          first_name: "Meredith",
          last_name: "Fontana",
          url: "https://media.licdn.com/dms/image/C4E03AQFa0C4W1juD4Q/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=0JiAly2WH4V0yXQT2tdjyotJzbhlCVf0esVQw3g7Zis",
          accountUser_id: 20,
          rating_id: 20,
        },
        {
          first_name: "Kate",
          last_name: "Schaefer",
          url: "https://media.licdn.com/dms/image/C5603AQGIO4LplVXZmA/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=AQbIgK0qFB5K5iSA8SOaJhoYHEehyJaZmAxUrK0MGRw",
          accountUser_id: 21,
          rating_id: 21,
        },
        {
          first_name: "Justin",
          last_name: "Williams",
          url: "https://media.licdn.com/dms/image/C5603AQH8eDjYQ-Baxw/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=so1EWoQXdmRV0PQKa_SKC4Psw10GzUHMGncUQZVsVA0",
          accountUser_id: 22,
          rating_id: 22,
        },
        {
          first_name: "James",
          last_name: "Liang",
          url: "https://media.licdn.com/dms/image/C5103AQFEZJ2HnuAdGA/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=vGp7aNhnlCpSE0Dfg0wE9L1whB5NweZLLR6CNCkX0S0",
          accountUser_id: 23,
          rating_id: 23,
        },
        {
          first_name: "Grant",
          last_name: "Fogle",
          url: "https://media.licdn.com/dms/image/C4E03AQH2I7CUuhnm3A/profile-displayphoto-shrink_800_800/0?e=1550707200&v=beta&t=-rZOHGDflxjEiVj6WbwuC1OLIEi54gmuvfJiMpPExHc",
          accountUser_id: 24,
          rating_id: 24,
        }
      ]);
    });
};